version: '3'
services:
  build:
    build:
      context: ./build
    environment: 
      EMAIL_ADDR: johannes.wenzel@web.de
      ROBOT_TYPE: s5
      FIRMWARE_VERSION: v11_001886.fullos.pkg
      NTP_SERVER: 192.168.178.1
    # volumes:
    #   - ./build:/app/rockrobo
    cap_add:
      - ALL
    security_opt:
      - apparmor:unconfined
    
    command: ./create-image.sh

  command:
    image: pyhton:3.8.1-buster
